"""Cover Letters API: generation and management."""

from __future__ import annotations

from typing import Literal
from uuid import UUID

from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import joinedload

from app.db.models import CoverLetter, Job, Resume
from app.dependencies import DB, CurrentUser
from app.schemas import CoverLetterRead
from app.services.intelligence.cover_letter import generate_cover_letter_content

router = APIRouter(prefix="/cover-letters", tags=["cover-letters"])


class GenerateCoverLetterRequest(BaseModel):
    job_id: UUID
    resume_id: UUID | None = None
    mode: Literal["cover_letter", "email"] = "cover_letter"


@router.post("/generate", response_model=CoverLetterRead, status_code=status.HTTP_201_CREATED)
async def generate_cover_letter(body: GenerateCoverLetterRequest, user: CurrentUser, db: DB):
    """Generate a targeted cover letter or cold recruiter email for a job."""
    # 1. Fetch job with company eager-loaded
    job = (
        await db.execute(
            select(Job).options(joinedload(Job.company)).where(Job.id == body.job_id)
        )
    ).unique().scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    # 2. Fetch resume (or user's master resume)
    if body.resume_id:
        resume = (
            await db.execute(select(Resume).where(Resume.id == body.resume_id, Resume.user_id == user.id))
        ).scalar_one_or_none()
    else:
        resume = (
            await db.execute(select(Resume).where(Resume.user_id == user.id).order_by(Resume.is_master.desc()))
        ).scalars().first()

    if not resume:
        raise HTTPException(status_code=400, detail="No resume found. Please upload a resume first.")

    # 3. Generate letter content
    company_name = job.company.name if job.company else "the team"
    letter_text = await generate_cover_letter_content(
        resume_content=resume.content,
        job_title=job.title,
        company_name=company_name,
        job_description=job.description,
        mode=body.mode,
    )

    # 4. Save to DB
    cl = CoverLetter(
        user_id=user.id,
        job_id=job.id,
        content=letter_text,
        format=body.mode,
    )
    db.add(cl)
    await db.flush()

    return CoverLetterRead.model_validate(cl)


@router.get("/", response_model=list[CoverLetterRead])
async def list_cover_letters(user: CurrentUser, db: DB):
    """List all cover letters generated by the current user."""
    result = await db.execute(
        select(CoverLetter).where(CoverLetter.user_id == user.id).order_by(CoverLetter.created_at.desc())
    )
    return [CoverLetterRead.model_validate(cl) for cl in result.scalars().all()]


@router.get("/{letter_id}", response_model=CoverLetterRead)
async def get_cover_letter(letter_id: UUID, user: CurrentUser, db: DB):
    """Get a specific cover letter."""
    cl = (
        await db.execute(select(CoverLetter).where(CoverLetter.id == letter_id, CoverLetter.user_id == user.id))
    ).scalar_one_or_none()
    if not cl:
        raise HTTPException(status_code=404, detail="Cover letter not found")
    return CoverLetterRead.model_validate(cl)


@router.delete("/{letter_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_cover_letter(letter_id: UUID, user: CurrentUser, db: DB):
    """Delete a cover letter."""
    cl = (
        await db.execute(select(CoverLetter).where(CoverLetter.id == letter_id, CoverLetter.user_id == user.id))
    ).scalar_one_or_none()
    if not cl:
        raise HTTPException(status_code=404, detail="Cover letter not found")
    await db.delete(cl)
